### ISSUE TITLE
Open projects in new tab

### ISSUE THREAD

**Issue by pranitbauva1997** [xypnox/xypnox.github.io#1]
When I click on a project link, it takes me from your site to GitHub. I think opening those links in a new tab would be better. It looks like you aren't using the `<a>` tag but instead an `onClick` handler on the `<div>` tag which could be fixed by following [this StackOverflow link](https://stackoverflow.com/questions/22856635/how-do-i-make-a-div-link-open-in-a-new-tab-javascript-onclick-window-location).

I usually try to open links with the middle button on mouse (the one with scroll bar) and it looks like it doesn't allow me to open links written in this way.

**Comment by xypnox** [comment]
Resolved
